/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author PC
 */
public class ConfiguracionC extends javax.swing.JPanel {
    
    private ProyectoFinalVistaVerde framePrincipal;
    private JTextField txtNuevaCuota;

    /**
     * Creates new form ConfiguracionC
     */
    public ConfiguracionC(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    
    private void configurarPantalla() {
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(15, 15, 15, 15);

        JLabel lblTitulo = new JLabel("Configuración de Cuota");
        lblTitulo.setFont(new Font("Times new Roman", Font.BOLD, 30));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        add(lblTitulo, gbc);

        gbc.gridwidth = 1; gbc.gridy = 1;
        add(new JLabel("Monto actual de la cuota (Q):"), gbc);
        
        txtNuevaCuota = new JTextField("1500.00", 10); 
        gbc.gridx = 1;
        add(txtNuevaCuota, gbc);

        JButton btnGuardar = new JButton("Actualizar Monto");
        btnGuardar.setBackground(new Color(52, 152, 219));
        btnGuardar.setForeground(Color.WHITE);
        gbc.gridx = 0; gbc.gridy = 2; gbc.gridwidth = 2;
        add(btnGuardar, gbc);

        JButton btnVolver = new JButton("Volver al Inicio");
        gbc.gridy = 3;
        add(btnVolver, gbc);

        btnVolver.addActionListener(e -> framePrincipal.cambiarPantalla("Inicio"));
        
        btnGuardar.addActionListener(e -> {
            try {
                double nuevoMonto = Double.parseDouble(txtNuevaCuota.getText());
                JOptionPane.showMessageDialog(this, "Cuota actualizada a: Q" + nuevoMonto);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese un monto válido.");
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
