/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author PC
 */
public class EstadoCC extends javax.swing.JPanel {
    private ProyectoFinalVistaVerde framePrincipal;
    private JComboBox<Integer> cbCasas;
    private JTextArea txtDetalle;
    private JLabel lblPropietario;
    private JLabel lblTotalPagado;

    /**
     * Creates new form EstadoCC
     */
    public EstadoCC(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    private void configurarPantalla() {
        setLayout(new BorderLayout(20, 20));
        setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JPanel panelNorte = new JPanel(new FlowLayout());
        panelNorte.add(new JLabel("Seleccione Número de Casa:"));
        
        Integer[] casas = new Integer[30];
        for (int i = 0; i < 30; i++) casas[i] = i + 1;
        cbCasas = new JComboBox<>(casas);
        panelNorte.add(cbCasas);
        
        JButton btnConsultar = new JButton("Consultar");
        panelNorte.add(btnConsultar);
        add(panelNorte, BorderLayout.NORTH);

        JPanel panelCentro = new JPanel(new GridLayout(1, 1));
        txtDetalle = new JTextArea();
        txtDetalle.setEditable(false);
        txtDetalle.setFont(new Font("Monospaced", Font.PLAIN, 13));
        panelCentro.add(new JScrollPane(txtDetalle));
        add(panelCentro, BorderLayout.CENTER);

        JPanel panelSur = new JPanel(new GridLayout(3, 1));
        lblPropietario = new JLabel("Propietario: ---");
        lblTotalPagado = new JLabel("Total Pagado: Q 0.00");
        JButton btnVolver = new JButton("Volver al Inicio");
        
        panelSur.add(lblPropietario);
        panelSur.add(lblTotalPagado);
        panelSur.add(btnVolver);
        add(panelSur, BorderLayout.SOUTH);

        btnVolver.addActionListener(e -> framePrincipal.cambiarPantalla("Inicio"));
        btnConsultar.addActionListener(e -> mostrarEstado());
    }

    private void mostrarEstado() {
        int casa = (int) cbCasas.getSelectedItem();
        lblPropietario.setText("Propietario: [Nombre de la Casa " + casa + "]");
        
        String reporte = "--- MESES PAGADOS ---\n";
        reporte += "Enero 2026 - Q1500.00\n"; 
        reporte += "\n--- MESES PENDIENTES ---\n";
        reporte += "Febrero, Marzo, Abril...\n";
        
        txtDetalle.setText(reporte);
        lblTotalPagado.setText("Total Pagado: Q 1500.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
