/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author PC
 */
public class Login extends javax.swing.JPanel {
    private JTextField txtUsuario;
    private JPasswordField txtContraseña;
    private ProyectoFinalVistaVerde framePrincipal;

    /**
     * Creates new form Logn
     */
    public Login(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
     
        setLayout(new GridBagLayout()); 
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lblTitulo = new JLabel("LOGIN CONDOMINIO VISTA VERDE", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Times new Roman", Font.BOLD, 38));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        add(lblTitulo, gbc);
        
        gbc.gridwidth = 1; gbc.gridy = 1;
        add(new JLabel("INGRESE SU USUARIO:"), gbc);
        txtUsuario = new JTextField(20);
        gbc.gridx = 1;
        add(txtUsuario, gbc);
 
        gbc.gridx = 0; gbc.gridy = 2;
        add(new JLabel("INGRESE SU CONTRASEÑA:"), gbc);
        txtContraseña = new JPasswordField(20);
        gbc.gridx = 1;
        add(txtContraseña, gbc);
        
        JButton btnIngresar = new JButton("INGRESAR");
        btnIngresar.setFont(new Font("Times new Roman ", Font.BOLD, 14));
        gbc.gridx = 0; gbc.gridy = 3; gbc.gridwidth = 2;
        add(btnIngresar, gbc);

        btnIngresar.addActionListener(e -> {
            String Usuario = txtUsuario.getText();
            String Contraseña = new String(txtContraseña.getPassword());
                
                if (Usuario.equals("iusr_vistaverde") && Contraseña.equals("R3sidencial2026%")) {
                JOptionPane.showMessageDialog(this, "Bienvenido!");
                
                framePrincipal.cambiarPantalla("Inicio");
                
            } else {
              
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
