/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author PC
 */
public class CasasM extends javax.swing.JPanel {
    
    private ProyectoFinalVistaVerde framePrincipal;
    private JTable tablaMorosos;
    private DefaultTableModel modelo;

    /**
     * Creates new form CasasM
     */
    public CasasM(ProyectoFinalVistaVerde frame){
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    
    private void configurarPantalla() {
        setLayout(new BorderLayout(15, 15));
        setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JLabel lblTitulo = new JLabel("LISTADO DE CASAS MOROSAS", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Times new Roman", Font.BOLD, 32));
        lblTitulo.setForeground(new Color(192, 57, 43)); 
        add(lblTitulo, BorderLayout.NORTH);
        
        String[] columnas = {"Casa #", "Propietario", "Teléfono", "Meses Atrasados"};
        modelo = new DefaultTableModel(columnas, 0);
        tablaMorosos = new JTable(modelo);
        JScrollPane scrollPane = new JScrollPane(tablaMorosos);
        add(scrollPane, BorderLayout.CENTER);

        JPanel panelSur = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton btnVolver = new JButton("Volver al Inicio");
        btnVolver.setPreferredSize(new Dimension(150, 40));
        
        panelSur.add(btnVolver);
        add(panelSur, BorderLayout.SOUTH);

        btnVolver.addActionListener(e -> framePrincipal.cambiarPantalla("Inicio"));
    }

    public void actualizarListaMorosos(Object[][] datosMorosos) {
        modelo.setRowCount(0); // Limpia la tabla
        for (Object[] fila : datosMorosos) {
            modelo.addRow(fila);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
