/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.Locale;
/**
 *
 * @author PC
 */
public class Inicio extends javax.swing.JPanel {
    
    private ProyectoFinalVistaVerde framePrincipal;
    /**
     * Creates new form Inicio
     */
    public Inicio(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    
    private void configurarPantalla() {
        setLayout(new BorderLayout());
        setBackground(new Color(245, 245, 245));

        JPanel panelN = new JPanel(new GridLayout(3, 1));
        panelN.setBackground(new Color(46, 204, 113));
        
        JLabel lblCondominio = new JLabel("CONDOMINIO VISTA VERDE", SwingConstants.CENTER);
        lblCondominio.setFont(new Font("Times new Roman", Font.BOLD, 28));
        lblCondominio.setForeground(Color.WHITE);

        JLabel lblBienvenida = new JLabel("Bienvenido", SwingConstants.CENTER);
        lblBienvenida.setFont(new Font("Times new Roman", Font.PLAIN, 26));
        lblBienvenida.setForeground(Color.WHITE);

        LocalDate fechaActual = LocalDate.now();
        String mes = fechaActual.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES"));
        int año = fechaActual.getYear();
        JLabel lblFecha = new JLabel("Tiempo: " + mes.toUpperCase() + " " + año, SwingConstants.CENTER);
        lblFecha.setFont(new Font("Times new Roman ", Font.ITALIC, 14));
        lblFecha.setForeground(Color.WHITE);panelN.add(lblCondominio);
        panelN.add(lblBienvenida);
        panelN.add(lblFecha);

        JPanel panelC = new JPanel(new GridLayout(3, 2, 20, 20));
        panelC.setBorder(BorderFactory.createEmptyBorder(40, 40, 40, 40));
        panelC.setBackground(Color.WHITE);
        
        JButton btnRegistroP = btnBoton("Registro Propietarios");
        btnRegistroP.addActionListener(e -> framePrincipal.cambiarPantalla("Registro Propietarios"));
        panelC.add(btnRegistroP);
        
        JButton btnRegistroPC = btnBoton("Registro de Pagos");
        btnRegistroPC.addActionListener(e -> framePrincipal.cambiarPantalla("Registro Pagos"));
        panelC.add(btnRegistroPC);
        
        JButton btnConfiguracionC = btnBoton("Configuracion de cuota");
        btnConfiguracionC.addActionListener(e -> framePrincipal.cambiarPantalla("Configuracion Cuenta"));
        panelC.add(btnConfiguracionC);
        
        JButton btnEstadoC = btnBoton("Estado de Cuenta");
        btnEstadoC.addActionListener(e -> framePrincipal.cambiarPantalla("Estado Cuenta"));
        panelC.add(btnEstadoC);
        
        JButton btnReporteG = btnBoton("Reporte General");
        btnReporteG.addActionListener(e -> framePrincipal.cambiarPantalla("Reporte General"));
        panelC.add(btnReporteG);
        
        JButton btnCasasM = btnBoton("Casas Morosas");
        btnCasasM.addActionListener(e -> framePrincipal.cambiarPantalla("Casas Morosas"));
        panelC.add(btnCasasM);
        
        add(panelN, BorderLayout.NORTH);
        add(panelC, BorderLayout.CENTER);
    }
    
    private JButton btnBoton(String texto) {
        JButton boton = new JButton(texto);
        boton.setFont(new Font("Arial", Font.BOLD, 14));
        boton.setFocusPainted(false);
        return boton;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
