/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author PC
 */
public class RegistroPC extends javax.swing.JPanel {
    
    private ProyectoFinalVistaVerde framePrincipal;
    private JComboBox<Integer> cbCasas;
    private JComboBox<String> cbMeses;
    private JTextField txtMonto; 
    private JTextField txtAnio;

    /**
     * Creates new form RegistroPC
     */
    public RegistroPC(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    
    private void configurarPantalla() {
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lblTitulo = new JLabel("Registro Pagos de Cuotas", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Times new Roman", Font.BOLD, 28));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        add(lblTitulo, gbc);

        gbc.gridwidth = 1; gbc.gridy = 1;
        add(new JLabel("Número de Casa:"), gbc);
        Integer[] casas = new Integer[30];
        for (int i = 0; i < 30; i++) casas[i] = i + 1;
        cbCasas = new JComboBox<>(casas);
        gbc.gridx = 1;
        add(cbCasas, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        add(new JLabel("Mes a pagar:"), gbc);
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        cbMeses = new JComboBox<>(meses);
        gbc.gridx = 1;
        add(cbMeses, gbc);

        gbc.gridx = 0; gbc.gridy = 3;
        add(new JLabel("Año:"), gbc);
        txtAnio = new JTextField("2026");
        gbc.gridx = 1;
        add(txtAnio, gbc);

        gbc.gridx = 0; gbc.gridy = 4;
        add(new JLabel("Monto de Cuota (Q):"), gbc);
        txtMonto = new JTextField("1500.00"); 
        txtMonto.setEditable(false); 
        txtMonto.setBackground(new Color(235, 235, 235));
        gbc.gridx = 1;
        add(txtMonto, gbc);

        JButton btnPagar = new JButton("Registrar Pago");
        btnPagar.setBackground(new Color(46, 204, 113));
        btnPagar.setForeground(Color.WHITE);
        gbc.gridx = 0; gbc.gridy = 5; gbc.gridwidth = 2;
        add(btnPagar, gbc);

        JButton btnVolver = new JButton("Volver al Inicio");
        gbc.gridy = 6;
        add(btnVolver, gbc);

        btnVolver.addActionListener(e -> framePrincipal.cambiarPantalla("Inicio"));
        btnPagar.addActionListener(e -> procesarPago());
    }
    private void procesarPago() {
        String msg = "Pago registrado para Casa " + cbCasas.getSelectedItem() +
        " - Mes: " + cbMeses.getSelectedItem();
        JOptionPane.showMessageDialog(this, msg);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
