/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author PC
 */
public class RegistroP extends javax.swing.JPanel {
    
    private ProyectoFinalVistaVerde framePrincipal;
    private JTextField txtNombre, txtTelefono, txtCorreo;
    private JComboBox<Integer> cbCasas;

    /**
     * Creates new form RegistroP
     */
    public RegistroP(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    
    private void configurarPantalla() {
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lblTitulo = new JLabel("Registro de Propietario", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Times new Roman ", Font.BOLD, 22));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        add(lblTitulo, gbc);

        gbc.gridwidth = 1; gbc.gridy = 1;
        add(new JLabel("Nombre Completo:"), gbc);
        txtNombre = new JTextField(20);
        gbc.gridx = 1;
        add(txtNombre, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        add(new JLabel("Número de Teléfono:"), gbc);
        txtTelefono = new JTextField(20);
        gbc.gridx = 1;
        add(txtTelefono, gbc);

        gbc.gridx = 0; gbc.gridy = 3;
        add(new JLabel("Correo Electrónico:"), gbc);
        txtCorreo = new JTextField(20);
        gbc.gridx = 1;
        add(txtCorreo, gbc);

        gbc.gridx = 0; gbc.gridy = 4;
        add(new JLabel("Número de Casa:"), gbc);
        
        Integer[] casas = new Integer[30];
        for (int i = 0; i < 30; i++) casas[i] = i + 1; 
        cbCasas = new JComboBox<>(casas);
        gbc.gridx = 1;
        add(cbCasas, gbc);
        
        JButton btnGuardar = new JButton("Guardar Registro");
        btnGuardar.setBackground(new Color(46, 204, 113));
        btnGuardar.setForeground(Color.WHITE);
        gbc.gridx = 0; gbc.gridy = 5; gbc.gridwidth = 2;
        add(btnGuardar, gbc);

        JButton btnVolver = new JButton("Volver al Inicio");
        gbc.gridy = 6;
        add(btnVolver, gbc);

        btnVolver.addActionListener(e -> framePrincipal.cambiarPantalla("Inicio"));

        btnGuardar.addActionListener(e -> {
            validarRegistro();
        });
    }
    
    private void validarRegistro() {
        if (txtNombre.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
        } else {
            JOptionPane.showMessageDialog(this, "Propietario registrado con éxito " + cbCasas.getSelectedItem());
            limpiarCampos();
        }
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        cbCasas.setSelectedIndex(0);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
