/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalvistaverde;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author PC
 */
public class ReporteG extends javax.swing.JPanel {
    
    private ProyectoFinalVistaVerde framePrincipal;
    private JTable tablaReporte;
    private DefaultTableModel modelo;
    private JLabel lblTotalRecaudado;

    /**
     * Creates new form ReporteG
     */
    public ReporteG(ProyectoFinalVistaVerde frame) {
        this.framePrincipal = frame;
        initComponents();
        configurarPantalla();
    }
    private void configurarPantalla() {
        setLayout(new BorderLayout(10, 10));
        setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JLabel lblTitulo = new JLabel("REPORTE GENERAL", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Times new Roman ", Font.BOLD, 30));
        add(lblTitulo, BorderLayout.NORTH);

        String[] columnas = {"Casa #", "Propietario", "Estado Actual", "Total Pagado (Q)"};
        modelo = new DefaultTableModel(columnas, 0);
        tablaReporte = new JTable(modelo);
        JScrollPane scrollPane = new JScrollPane(tablaReporte);
        add(scrollPane, BorderLayout.CENTER);

        JPanel panelInferior = new JPanel(new GridLayout(2, 1, 10, 10));
        
        lblTotalRecaudado = new JLabel("Total Recaudado en el Mes: Q 0.00 / Esperado: Q 45,000.00", SwingConstants.RIGHT);
        lblTotalRecaudado.setFont(new Font("Times new Roman ", Font.BOLD, 16));
        lblTotalRecaudado.setForeground(new Color(41, 128, 185));

        JButton btnVolver = new JButton("Volver al Inicio");
        btnVolver.setPreferredSize(new Dimension(150, 40));

        panelInferior.add(lblTotalRecaudado);
        panelInferior.add(btnVolver);
        add(panelInferior, BorderLayout.SOUTH);

        btnVolver.addActionListener(e -> framePrincipal.cambiarPantalla("Inicio"));
        
      
    }

    public void cargarDatosSistema(Object[][] datos, double totalRecaudado) {
        modelo.setRowCount(0);
        for (Object[] fila : datos) {
            modelo.addRow(fila);
        }
        lblTotalRecaudado.setText("Total Recaudado: Q " + totalRecaudado + " / Esperado: Q 45,000.00");
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
